### ISSUE TITLE
Collect congressional data and create an interface to interact with it

### ISSUE THREAD

**Issue by saikat** [BrandNewCongress/welcome#1]
Ryan Hutto had started on this.  The proposal is a bit vague, but we want to start collecting our important congressional data to figure out how our research team will be working.

**Comment by dcampana** [comment]
I have setup the research team with a spreadsheet for the preliminary research on key issues but we need some sort of system that allows for more robust answers besides Support/Doesn't Support, especially for things that can't be clearly defined or need more detail.  I thought maybe a wiki would work but that might also get unwieldy with 600 different pages for such a relatively small amount of information.

**Comment by saikat** [comment]
My inclination here is that, since the scope of this is still a little
vague (e.g. we don't have a clear sense of what we are tracking and where
existing systems will break down for us), we should try to use an off the
shelf solution until it becomes unwieldy.  I want to make sure that if we
do build something here, that it is the right thing.  We should also figure
out what the issues are with the existing solutions that we would need to
solve (e.g. the 600 pages thing with a wiki isn't necessarily a problem
inherent to wikis -- it's a problem inherent to us having lots of data.
Maybe the issue then is really that wikis don't have great search
capability?)

Some possible solutions:
- Wiki, as you mentioned.  That might be the easiest thing to start with.
- Some sort of CMS geared towards data collection and retrieval

I can ask a couple of my friends who have done a lot of political research
what system they use to keep track of the data they are collecting, in case
that helps!

**Comment by dcampana** [comment]
We will be at the point that we need a more robust system in the coming month or so.  Right now we are using this [spreadsheet](https://docs.google.com/spreadsheets/d/12m_w1B9Ww0kUiKnD4hDGYeN-DoHAuVLTqc1_nBdyfGY/edit#gid=0) and I feel its really limited with both access management, data logging, and data entry.  As this fills up we are going to need a more robust system to describe the nuances of issues marked unclear. 

Here are the features I would like:
- Access management to prevent people from maliciously removing or editing data
- Keyword sorting so we can sort by things such as Scandal, Corruption, Etc.
- Ability to easily add more politicians for when we need to add people who are running against the existing candidates.  

I think a wiki is the best approach unless we can make a custom tailored piece of software but that seems overkill for this.  Since its a google doc we can just scrape the relevant data and upload it to the wiki.

**Comment by saikat** [comment]
Yup -- I would say let's go the wiki route until that doesn't work for us.
It'll also give us a better sense of where the difficulties are in using a
wiki to know what we should focus on if we make some custom software.
Let's talk on the phone to talk through setting it up with Nina?  I'm on
slack as @saikat.

**Comment by AlaskanOracle** [comment]
Drupal might be a solution (http://www.drupal.org) also ties in well with CiviCRM (http://www.civicrm,org) and you can add wiki like features to it . :) also with its fieldable content and Views there is a lot of potential.

**Comment by saikat** [comment]
We use Nationbuilder more as our CRM than our CMS.

**Comment by kevin-vilbig** [comment]
Malicious editing isn't an issue as long as we keep track of the edits within the system and can rollback. Wikis can do this. Google docs can also do this.

But...

As long as we organize our spreadsheet in such a way that it is explicitly tabular, rather than having multiple tables, it will be simple to iterate over it with standard stats analytics tools, including tagging for keywords! Maybe, since you are already splitting things up to multiple tables because of technical issues (google docs rendering too slowly on large tables) on that spreadsheet you posted, we should think about another solution? Nationbuilder has an API. It will take some effort to learn it, but maybe that will be best, rather than building a bespoke DB system.

Spreadsheets can only go so far before they become a liability rather than a benefit.

**Comment by saikat** [comment]
Google Sheets is able to handle tens of thousands of rows pretty easily.
I'd start with sheets just so we can play around with different ideas and
models first before sticking it into a database.  Once we start making SQL
models, it'll be harder to be as flexible.

**Comment by saikat** [comment]
@dcampana I think what might make sense here (and not sure if this is something you are already working on) is to create something of a longish-term plan for the research team of what you will be collecting and how.  This will probably need to be in conjunction with the larger plan that Brand New Congress needs to make for the group. It'll help us plan a bit on the tech needs.

**Comment by sgrimsley** [comment]
I was looking at the research team application, and found some of the data can be acquired in bulk through the FEC or GovTrack.us.  (Candidate info, financial data, votes, committee membership.)

I know how I'd approach the data collection / interface issue for me, but am not sure if that'd scale for BNC.
