### ISSUE TITLE
Events map

### ISSUE THREAD

**Issue by yihpin** [BrandNewCongress/welcome#10]
## Launch Todos
- View map (UI of https://map.berniesanders.com)
  - Map 
  - Zoom map by zipcode
  - Filter by event type
  - Search by event name
  - Show list of events based on filters/search
- Create event view for hosts
- Edit event view for hosts
- RSVP view for attendees
- Admin for rejecting events
- Authentication for creating events
- RSVP email gets a confirmation email so you can contact us if this was incorrect
- Create event
  - if your email doesn’t exist, create account and ask for pw and take to my events
  - if it does exist, ask you to sign in w/ your pw

## Data
  - Event objects
    - location
      - PostGIS
    - name
    - creator ID
    - FB link? 
    - date & time
  - RSVP objects?
    - Name
    - email
    - event ID

## Tech Stack
- Postgres
- Elixir
- React
- Graphql
- Apollo

## Future todos
- List of people who attended event
- Automated reminders
- A way to add some documentation/resources on the “Host an Event” or "My Events" pages. Or a way to e-mail them with information about how to host the event type they decided to host. Or both.
- Ability for organizations other than Brand New Congress to sign up, create their own event map, and add their own styles to style the map.

**Comment by saikat** [comment]
Are you thinking we make our own event system that people use entirely and it just feeds data in, via API, to other systems like FB, NB, etc.?  I like it!  I'm going to approve this -- we should come up with a plan for an MVP if we can find a dev to take this on.

**Comment by saikat** [comment]
This should tie in to a general purpose event map, so I'm bringing that issue in here too.  Notes from that issue:

Things we need (this is updated from comments below, so if you don't have time to read through all the comments, you can just look at this).

 Make a map with the same UI as https://map.berniesanders.com but with, for now, one event type (Sept 20th Livestream)
 Have different colored dots for events of different sizes and types (Under 20 ppl, Over 20 ppl, Official event, College event)
 Have the "Host an Event" button go to a page with resources for how to host an event. These can just be online versions of what exists in brandnewcongress.org/work
 Suggestions for layout on https://gomockingbird.com/projects/5tcim6p/4gXVnC
 Let people create events
 Let people RSVP for events
 Add a link to the map from the homepage
 make it more zoom in friendly (the dots stay the same size when zooming in, they don't get smaller)
 zoom the actual map out, as right now CA has cut off event titles
 make a link for the events down below the map, and have that separated out by state.
 Add the ability to search by zip code, state or city for an event
I'm currently thinking that the map should be a new standalone app instead of being a part of the website. This would also mean making a brandnewcongress-starter-kit that has the common resources (themes, navbar, etc.) that we could use between website and the new app. I will likely use https://github.com/saikat/react-apollo-starter-kit as the starting point.

**Comment by saikat** [comment]
Would also be cool to have an option for people to sign up and let their info be public on the map and show people all the people in their area.
