### ISSUE TITLE
Clean up our Google Analytics

### ISSUE THREAD

**Issue by saikat** [BrandNewCongress/welcome#24]
Goals:
* See sources of traffic to different pages/to the site as a whole
* See which Facebook posts/emails/etc. are driving traffic
* See the funnels leading to sign ups and donations

**Comment by ghost** [comment]
I'm able to contribute to this. I've been using analytics tools for years, and G Analytics since day one. I will need an admin on your end to enter my email (bmadiuk@gmail.com) to the user access list so I can start. 

I will also need a list of pages you want to set as "goals", meaning which pages are the end point you want. A good example would be: store thank you page, contact form submission, donation submissions, etc. 

In order to fully integrate the analytics, if you use an off-site tool such as act-blue I will need backend access to install the tracker code there as well.

If you'd like to add me to Slack, that may be the easiest way to track progress and requests as this isn't so much a tech issue (very little if any coding involved)

**Comment by saikat** [comment]
Hey sorry -- actually already fixed this one.  Forgot to close it out!
