### ISSUE TITLE
Team management tool based on Slack

### ISSUE THREAD

**Issue by saikat** [BrandNewCongress/welcome#7]
We want a way for people to be given permissions to stuff based on what slack channel they are get invited into. Basically slack is the admin interface for our teams.  Maybe this is an extension to https://github.com/BrandNewCongress/slack-teams.  /cc @adamhowardprice.  Here's a rough list of features that would be nice:
- [ ] A way to add or remove someone from a team
- [ ] A slackbot that tells people who is on what team and who runs which team
- [ ] A way to see who is in the slack but not on a team
- [ ] A way to see, for a given person, what teams that person is on

When someone gets added to a team it:
- [ ] Gives that person permissions defined for that team for a variety of tools used by that team such as:
  - [ ] Nationbuilder
  - [ ] A lastpass folder
  - [ ] Google Drive
  - [ ] Github
  - [ ] Invitation to a particular slack team or channel
  - [ ] A way to report progress everyday
- [ ] Adds person to other things that person needs to know about
  - [ ] Standing meetings for that team on google calendar

**Comment by saikat** [comment]
One thing that could be interesting -- we have a need on http://dashboard.brandnewcongress.org/ to be able to manually submit some numbers.  E.g. eventually we want dashboards for each team, and the metric for a team may have to be manually submitted (for the events team right now, maybe we would want to track everyday how many events we've found venues for).  What if this slackbot was also the way to do that?  And we could then just have certain volunteers whose sole job is updating that metric everyday via something like /teambot <metric> <number> just sets the number for that day.  What do you guys think of this idea @evanhl and @traviskaufman

**Comment by evanhl** [comment]
I like the idea of a Slackbot that does that, but then again, I'm used to a command line. It is a nice temporary solution to account management, though. Everyone already has slack accounts, and I'm assuming the bot can support some kind of whitelist or account permissions.

**Comment by traviskaufman** [comment]
Both ideas sound good. It seems like a sound strategy might be to create some sort of service that multiple clients could interface with. For example, an organization management API that could be used by a slack bot, CLI tool, GUI, or otherwise. I don't think it would be that much more difficult to set up and it would allow us to easily experiment with a lot of different interfaces

**Comment by saikat** [comment]
@traviskaufman think you can digitize and add your notes from the speccing meeting to this issue?  I think it's ok if it's just photos of what you took -- just as a refresher for when we come back to this.  I'm assigning you to this issue for now.

**Comment by traviskaufman** [comment]
For sure. I'll post them up on the issue tonight

**Comment by saikat** [comment]
An interesting feature here (as referred to by #5) would be a way for people to schedule their shifts.  Basically a way for people to indicate when they will do work/be on call, and then a way for people to check who on a team is on call at any given time.  This would be something that's unique to our particular org, I think, since we are basically an organization made of part-time workers and leaders.

**Comment by traviskaufman** [comment]
From my discussions with @saikat this week:

## Background
- Cross-team communication for BNC members is tricky
- Visibility into teams and team leadership is difficult
- Onboarding is fragmented across teams
- Process management is fragmented and ambiguous due to organic growth of teams

## Overview

We propose `bnc-teams`, a slack interface that acts as a team management tool, most likely implemented as a slack command
- Should have an ACL for team leads only
- Can assist with onboarding
- Can manage proper permissions for NationBuilder and GDrive

## Onboarding flow
1. User views available opportunities within /teams
2. User fills out sign up form for volunteering.
3. Info gets POSTed to NationBuilder (**NB**)
4. Team Lead (**TL**) manually goes through signups via NB
5. TL selects potential candidates and performs initial call
6. TL takes candidate through interview
7. Barring success, TL accepts candidate onto team _(NOTE: This is where bnc-teams would kick in)_
8. TL uses bnc-teams slack command to add user to team and kick off onboarding process

### Likely Commands

#### /bnc-teams add &lt;email&gt;

Adds a user to a team, identified by `<email>`
- Sends off a slack invite
- Sends them a welcome email with onboarding information
- Configures permissions for their account
- Email uniquely IDs user

#### /bnc-teams add-lead &lt;email&gt;

Makes a user identified by `<email>` a team leada
- Assumes user is already part of team
- There can be more than one TL at a time. This is to facilitate transitions.

#### /bnc-teams rm &lt;email&gt;

Removes a user identified by `<email>` from a team
- Handles ACLs/permissions regarding such
- Does not kick them from Slack altogether

#### /bnc-teams rm-lead &lt;email&gt;

Removes a user as a team lead
- Keeps them on the team

#### /bnc-teams ban &lt;email&gt;

Nuclear option
- rm all permissions and ACL for user and kick them from slack

#### /bnc-teams list [team-channel]

Lists all of the members (and their roles) of a certain team 
- `team-channel` can be specified to list members of a specific team
- defaults to the team of the channel the command is run from, assuming that channel is associated with a team

#### /bnc-teams help

Shows the commands and their usages

## Next steps
- [ ] Research existing solutions to team directory management tools 
- [ ] Research most cost-effective and efficient method of execution
- [ ] Create schema for teams/members/permissions

**Comment by saikat** [comment]
An extension to this project would be to add ways for team members to track work.  I'm imagining that each team would have a goal and, in addition, possibly each member of a team would have a goal.  So we would need:
* A way for a team to set a goal. Could be something daily, weekly, or one-time.  To keep things simple, we should just make it numeric.
* A way for a team leader to set a goal for each team member.
* A way to view the current goal.
* A way to log work.  This could be as simple as submitting a number everyday. One thing to think about is that we explicitly want to make contacting individuals on the team a goal, so not sure how that fits into the generic 'log a number' model.  E.g. we want to make sure every deputy team leader has contacted everyone in their group 2x a week.
* A way to view progress towards goals.

**Comment by saikat** [comment]
This project will mostly be formalizing the manual processes that Haley is doing with the Volunteer Recruitment team.
