### ISSUE TITLE
Auto-dialer

### ISSUE THREAD

**Issue by saikat** [BrandNewCongress/welcome#9]
This is a very big project.  There are existing autodialers out there (HubDialer is popular), though most of them can only call landlines.  There are some that can call cell phones (LiveVox) but have pretty crappy interfaces and no inline scripting. 

The goals here are:
- [ ] Call landlines and cell phones
- [ ] Degrade gracefully when there aren't enough people calling
- [ ] Inline scripting
- [ ] Score keeping/gamification

**Comment by jordanstreiff** [comment]
What about a browser plugin to work with LiveVox? We could reskin / improve the interface and also tie in with NationBuilder API.

**Comment by saikat** [comment]
Possibly!  So to add a bit more context here, this is a long term project.  We don't have immediate need for an auto-dialer (and we could probably use an off-the shelf one).  I think at the point that the browser plugin also starts handling graceful degradation for when there aren't enough users on board and inline scripts, we will end up facing more challenges integrating with LiveVox than just making our own backend.  Also, browser plugins tend to be not as heavily used as just a webapp.  So basically -- I think if we need a dialer in the short term, we should just use something off the shelf.  But given that we maybe will have some dev capacity, it would be cool to make a good, open source dialer as a longer term project.

**Comment by lakshbhasin** [comment]
Seems like we can reuse a lot of our functionality from BerniePB for a project like this (although we'd have to reorganize our front page to support candidates and candidate goals, instead of states). We probably won't be free to port that functionality for some time because we're still working on maintaining BerniePB, but a lot of the current gamification we have seems to work well and appeal to users.

I also took a quick look at the callaborate project (https://github.com/saikat/callaborate) and it looks like it uses Tropo (https://www.tropo.com/how-it-works/) to actually make the calls. It seems like it currently costs 1.5¢/min to make outgoing calls in the continental US. Doing some quick estimates, if the goal is to contact ~100M actual people (which I'm guessing would take something like 500M attempts due to low pick-up rates), the overall cost could end up being something like ~$10M. Based on that estimate, do you think it would make sense to maybe start off with Tropo so we can put together the rest of the dialing tool (interface, degradation logic, etc) and then migrate to an in-house tool that can handle all of Tropo's functionality at a much lower cost?

**Comment by seanmacalways** [comment]
I had been looking at their Tropo usage, too, and was a bit concerned about how the costs would scale. If I recall correctly from when I looked at it, though, it's free for prototyping, so we could probably start there without much penalty (unless some quirks about its implementation would accrue a lot of technical debt).

**Comment by saikat** [comment]
Does tropo make more sense to use than something like Twilio or Plivo?

**Comment by saikat** [comment]
Sounds good -- just trying to figure out how Tropo is different from Plivo
or Twilio.  Does it abstract away the auto-dialing part for us or something?

**Comment by saikat** [comment]
@seanmacalways @lakshbhasin are you guys still interested in trying to take on this big project?  It might be good to go through a more fully fleshed speccing session.  I'm actually in SF this week (I vaguely remember one of you being in Berkeley?) so could meet up to talk about it.

**Comment by seanmacalways** [comment]
@saikat Apologies on dropping he ball on this communication, I had already left Berkeley for ~9 days in Alaska (backpacking, so no comms access), immediately followed by People's Summit. To re-hash our conversation there, I think we're still definitely interested in developing this tool. Things are settling down for all of us now and more time should be available (though, first, we're trying to get up a down-ballot version of BerniePB for immediate use this election cycle).

In answer to your earlier question, as far as I can tell with a quick look Tropo et al. do not provide auto-dialing out of the box. They are mostly there to act as an abstraction layer for underlying telephony.

As an aside, how interested are we right now in text (e.g. like Hustle)? In discussions at People's Summit, seems like there are some very big gains that can be made there in terms of price reduction, and it also seems to have really good response rate.

**Comment by exzackley** [comment]
To answer a question above about whether costs scale: They do! Spending
10's of Millions on calling voters is appropriate in a campaign that will
cost hundreds of millions of dollars.

And in the short run, when we'll just be doing 10s of hours of calling, the
costs will be minimal at 1.5 cents per minute.

The sooner we can get a dialer started the better, because our capacity to
make calls will not take off without a dialer -- we learned that beyond
doubt with Bernie.

Zack

On Thu, Jun 23, 2016 at 6:21 AM, seanmacalways notifications@github.com
wrote:

> @saikat https://github.com/saikat Apologies on dropping he ball on this
> communication, I had already left Berkeley for ~9 days in Alaska
> (backpacking, so no comms access), immediately followed by People's Summit.
> To re-hash our conversation there, I think we're still definitely
> interested in developing this tool. Things are settling down for all of us
> now and more time should be available (though, first, we're trying to get
> up a down-ballot version of BerniePB for immediate use this election cycle).
> 
> In answer to your earlier question, as far as I can tell with a quick look
> Tropo et al. do not provide auto-dialing out of the box. They are mostly
> there to act as an abstraction layer for underlying telephony.
> 
> As an aside, how interested are we right now in text (e.g. like Hustle)?
> In discussions at People's Summit, seems like there are some very big gains
> that can be made there in terms of price reduction, and it also seems to
> have really good response rate.
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> https://github.com/BrandNewCongress/welcome/issues/9#issuecomment-228020502,
> or mute the thread
> https://github.com/notifications/unsubscribe/AAAXmSdxGPLWpRxbXlw9dBSsrq2RVuqSks5qOmw_gaJpZM4Ik8-s
> .

## 

Zack
